### ISSUE TITLE
标题更改：真题来源 注明出处

### ISSUE THREAD

**Issue by guoJohnny** [csseky/cskaoyan#1]
https://github.com/csseky/cskaoyan/blob/master/%E5%93%88%E5%B0%94%E6%BB%A8%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6/837/%E5%93%88%E5%B0%94%E6%BB%A8%E5%B7%A5%E4%B8%9A%E5%A4%A7%E5%AD%A6-837-2019-%E7%9C%9F%E9%A2%98%E5%9B%9E%E5%BF%86%E7%89%88.pdf

以上这个考研回忆版是来自我王道论坛的文章，可以分享，但请注明出处：
http://www.cskaoyan.com/thread-652587-1-1.html

**Comment by csseky** [comment]
同学您好。非常感谢您提出的问题。您回忆的考研真题并不是您编写的，是哈尔滨工业大学的老师编写的，是哈尔滨工业大学的劳动和智力成果。著作权属于他们。我们同样都是免费分享给大家。不过您和其他同学的回忆真题也是给同学们做出了很大的贡献，而且正是由于您的回忆，我们才有机会分享。因此我们会在下次Push的时候加入致谢模块。里面会包含您的帖子地址和github主页。非常感谢您的真题和建议。

**Comment by csseky** [comment]
同学您好，我们已经更新了致谢信息，里面包含您了的帖子地址和github主页。
地址：
https://github.com/csseky/cskaoyan/blob/master/Acknowledgement.md
由于时间有限，其余致谢信息会逐渐进行更新的。
非常感谢您的支持！
由于标题看起来比较不好，因此我修改了一下标题，抱歉

**Comment by guoJohnny** [comment]
OK，感谢理解，支持免费共享行为

**Comment by john8tom** [comment]
https://github.com/csseky/cskaoyan

**Comment by mingrongchen** [comment]
我已收到您的邮件，谢谢！

**Comment by Big-Data-and-Dogs** [comment]
wow ,so This is free?

**Comment by Merccccy** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
