### ISSUE TITLE
下载单独的文件或文件夹

### ISSUE THREAD

**Issue by lihaowu** [csseky/cskaoyan#18]
建议作者在Readme中加入直接下载某个文件或者文件夹的地址连接，方便只想下载某些文件的朋友
原版网站（国内可能打不开）：https://minhaskamal.github.io/DownGit/#/home
国内翻版网站：http://zhoudaxiaa.gitee.io/downgit/#/home

**Comment by csseky** [comment]
https://gitee.com/mirrors_csseky/cskaoyan

**Comment by csseky** [comment]
gitee上的镜像可以单独下载文件夹或者单独下载pdf，使用体验较好
