### ISSUE TITLE
建议改为 Creative Commons 协议

### ISSUE THREAD

**Issue by notfresh** [csseky/cskaoyan#3]
4. 我的开源项目不是代码建议： Creative Commons。
这是一个相对宽松的版权协议。它只保留几种了权利（some rights reserved）。使用者可以明确知道所有者的权利，不容易侵犯对方的版权，作品可以得到有效传播。作为作者，你可以选择以下1~4种权利组合:1. 署名（Attribution，简写为BY）：必须提到原作者。2. 非商业用途（Noncommercial，简写为NC）：不得用于盈利性目的。3. 禁止演绎（No Derivative Works，简写为ND）：不得修改原作品, 不得再创作。4. 相同方式共享（Share Alike，简写为SA）：允许修改原作品，但必须使用相同的许可证发布。

作者：童仲毅
链接：https://www.zhihu.com/question/28292322/answer/40238421
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

**Comment by csseky** [comment]
后续会考虑的
